# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/chagall-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter chagalllte chagallwifi,$(TARGET_DEVICE)),)

endif
